# GitHub Sponsors funding file
# Support the development of API Documentation Parser

github: # Add your GitHub username here if you want sponsorship
custom: ["https://buymeacoffee.com/api-doc-parser"] # Custom sponsorship links